apiVersion: apps/v1
kind: Deployment
metadata:
  name: webby-deployment
  labels:
    app: webby
spec:
  selector:
    matchLabels:
      app: webby
  replicas: 3
  template:
    metadata:
      labels:
        app: webby
    spec:
      containers:
      - name: webby
        image: reg.alta3.com/261-bolobas-webby
        ports:
        - containerPort: 80
